### ISSUE TITLE
datetime format issue

### ISSUE THREAD

**Issue by just-nilux** [5ymph0en1x/SyBrain#3]
Great stuff you are doing here! 
I ran into an issue I can't really resolve. When launching sybrain.py I get this error:

```
/usr/local/lib/python3.6/dist-packages/swagger_spec_validator/validator20.py:53: SwaggerValidationWarning: Found "$ref: #/definitions/UserPreferences" with siblings that will be overwritten. See https://stackoverflow.com/a/48114924 for more information. (path #/definitions/User/properties/preferences)
  ref_dict['$ref'], '/'.join(path),
It began in Africa...
Launching Machine learning Module...
Start: 2019-09-25 13:57:00 / End: 2019-09-25 14:02:00
time data '2019-09-25 13:57:00+00:00' does not match format '%Y-%m-%d %H:%M:%S%z'
 This is the end !
Traceback (most recent call last):
  File "sybrain.py", line 366, in <module>
    bmex()
  File "sybrain.py", line 275, in bmex
    while ws_bmex.ws.sock.connected:
AttributeError: 'NoneType' object has no attribute 'connected'
```

Any advise?

**Comment by 5ymph0en1x** [comment]
Hi !

Thanks for your comment.

I may have found a workaround for you :-)
Try this : in the file stockpredictor.py, add this line at line 91 : `j.replace('+00:00', '+0000')`

Tell me if it works !

**Comment by just-nilux** [comment]
Hey buddy, thanks for helping out. Unfortunately I still get the same error :/ 
I understand what's broken but can't really trace it back to a specific point where to fix this. Any other idea? The server date/time is set to UTC, so that should be consistent with the bitmex timestamps.

**Comment by 5ymph0en1x** [comment]
Hello dude, strange thing what is happening to you. I've tested this algo on win and linux but not on macos. I'm thinking about a platform-dependant issue. I remember reading some time ago about the %z being not fully universal. I would try replacing `%z` by `%Z`...
